Problem Statement - 1

Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the 'increasing' boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [72]:
import pandas as pd
import numpy as np

def gen_matrix(input_vector, n, increasing=False):

    if not increasing:
        output = np.array([x**(n-1-i) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    else:
        output = np.array([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size, n)
    
    return output


input_vector= np.array([1,2,3,4,5,6,7])

##  When Not Inreasing
output1= gen_matrix(input_vector, input_vector.size, False)

## When Increasing
output2 = gen_matrix(input_vector, input_vector.size, True)

print('When Decreasing ...  ')
print(output1)
print('\n')
print('When Increasing ...  ')
print(output2)


When Decreasing ...  
[[     1      1      1      1      1      1      1]
 [    64     32     16      8      4      2      1]
 [   729    243     81     27      9      3      1]
 [  4096   1024    256     64     16      4      1]
 [ 15625   3125    625    125     25      5      1]
 [ 46656   7776   1296    216     36      6      1]
 [117649  16807   2401    343     49      7      1]]


When Increasing ...  
[[     1      1      1      1      1      1      1]
 [     1      2      4      8     16     32     64]
 [     1      3      9     27     81    243    729]
 [     1      4     16     64    256   1024   4096]
 [     1      5     25    125    625   3125  15625]
 [     1      6     36    216   1296   7776  46656]
 [     1      7     49    343   2401  16807 117649]]


Problem Statement - 2

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
    
The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [73]:
def moving_Average(array , window):
   
   # Since , out Output Array contains n-k+1 values
   output = np.zeros(array.size - window + 1) 
    
   for i in range(window, array.size+1): 
      output[i-window] = array[i-window:i].mean()
   return output

result = moving_Average(np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]) , 3)

print(result)




[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
